### ISSUE TITLE
Issue while building the library

### ISSUE THREAD

**Issue by deepak2431** [textmagic/textmagic-rest-cpp-v2#1]
![Screenshot (241)](https://user-images.githubusercontent.com/44617923/76997610-93367380-6979-11ea-8215-390c606799b2.png)
![Screenshot (240)](https://user-images.githubusercontent.com/44617923/76997616-95003700-6979-11ea-8062-f68abc6d6486.png)
I am getting the following issue while building the library in visual code. Please help ASAP.

**Comment by deepak2431** [comment]
![Screenshot (243)](https://user-images.githubusercontent.com/44617923/76997874-0dff8e80-697a-11ea-921d-3164684992ff.png)
![Screenshot (242)](https://user-images.githubusercontent.com/44617923/76997875-0f30bb80-697a-11ea-8e61-7cb1ae3792c1.png)
These are the errors I am getting while building the library.

**Comment by imissyouso** [comment]
hi,
have you installed `libcpprest-dev` dependency (https://github.com/microsoft/cpprestsdk)?
For windows:
```
vcpkg install cpprestsdk cpprestsdk:x64-windows
```

**Comment by deepak2431** [comment]
Yeah 8I have installed it and our it into root of TextMagic

**Comment by imissyouso** [comment]
This library is generated by https://github.com/swagger-api/swagger-codegen , seems bug on their side.
I am investigating the issue...

**Comment by dmitry-textmagic** [comment]
@deepak2431 in the meantime, could you please try to use our previous version of the wrapper, not automatically generated but written on our own? https://github.com/textmagic/textmagic-rest-cpp

**Comment by imissyouso** [comment]
@deepak2431 version v2.0.1307 has been released, README.md has been updated too.
Please try to compile again.

**Comment by deepak2431** [comment]
![Screenshot (249)](https://user-images.githubusercontent.com/44617923/77092970-5a0d0a80-6a30-11ea-82bc-56111e99168b.png)
@imissyouso Still there is some issue please fix it ASAP. I am in an urgent need to integrate this to my application.

**Comment by deepak2431** [comment]
> 
> 
> @deepak2431 in the meantime, could you please try to use our previous version of the wrapper, not automatically generated but written on our own? https://github.com/textmagic/textmagic-rest-cpp

You need to fix this too. There are errors in this library too :)

**Comment by imissyouso** [comment]
> Still there is some issue please fix it ASAP. I am in an urgent need to integrate this to my application.

I think something wrong with your configuration of boost library, similar is described here https://stackoverflow.com/questions/3163935/fatal-error-c1083-cannot-open-include-file-boost-regex-hpp-no-such-file-or

`random_generator.hpp` it is a part of boost uuid library (https://www.boost.org/doc/libs/1_64_0/libs/uuid/), does your boost installation contains it?

also similar issue is described here microsoft/vcpkg#277

furthermore I found in swagger codegen documentation that it requires Boost version 1.45.0, I guess your Boost version is too new, try to downgrade it.

**Comment by imissyouso** [comment]
similar issue is described here https://github.com/Microsoft/vcpkg/issues/277

**Comment by imissyouso** [comment]
also I found in swagger codegen documentation that it requires Boost version 1.45.0 , I guess your Boos version is too new, try to downgrade it.

**Comment by deepak2431** [comment]
![Screenshot (254)](https://user-images.githubusercontent.com/44617923/77248458-7a6edc00-6c5f-11ea-8b59-4e1880a3c7c7.png)
@imissyouso  Everything is fine now. Still getting just one issue can you please help fixing me this issue as I couldn't find any solution online for this too?

**Comment by dmitry-textmagic** [comment]
@deepak2431 this issue is about Visual Studio and Boost library compatibility and it is not related to our cpp wrapper. Unfortunately, we can't assist you with the third-party code. 

However, could you please try to use some of these solutions: https://stackoverflow.com/questions/43245055/issue-with-boost-1-64-and-visual-studio-2017/48965738
